[package]
name = "download-yahoo"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
reqwest = { version = "0.12.9", features = ["blocking", "json"] }
serde_json = { version = "1.0.133", features = ["std"] }
